// @nvhash/api-types — the shared freshness-envelope contract for the nvHASH App
// (ADR-001 Decision 4). Producer: services/api. Consumers:
// services/api and apps/web. Zero runtime dependencies.

export {
  envelope,
  freshness,
  type Envelope,
  type FreshnessInput,
  type FreshnessMeta,
  type FreshnessSource,
} from "./envelope.ts";
export {
  GOVERNANCE_BOUNDED_FIELDS,
  MARKER_CAP,
  MARKER_CAP_WIRE,
  MAX_ACCRUAL_POINTS,
  MAX_ACCRUAL_POINTS_WIRE,
  MAX_BECH32_LENGTH,
  MAX_GOV_METADATA_LENGTH,
  MAX_GOV_POLICIES,
  MAX_GOV_POLICIES_WIRE,
  MAX_GOV_PROPOSAL_MESSAGES,
  MAX_GOV_PROPOSAL_MESSAGES_WIRE,
  MAX_GOV_PROPOSALS_PAGE,
  MAX_GOV_PROPOSALS_PAGE_WIRE,
  MAX_GOV_PROPOSERS,
  MAX_GOV_PROPOSERS_WIRE,
  MAX_GOV_SUMMARY_LENGTH,
  MAX_GOV_TITLE_LENGTH,
  MAX_GOV_VOTES_PER_PROPOSAL,
  MAX_GOV_VOTES_PER_PROPOSAL_WIRE,
  MAX_PROPOSAL_MESSAGES,
  MAX_PROPOSAL_METADATA_LEN,
  MAX_PROPOSAL_SUMMARY_LEN,
  MAX_PROPOSAL_TITLE_LEN,
  MAX_TXHASH_LENGTH,
  MAX_YIELD_POINTS,
  MAX_YIELD_POINTS_WIRE,
  WIRE_BOUNDS,
  WRITE_READ_BOUNDS,
  type WireBound,
  type WriteReadBound,
} from "./bounds.ts";
export {
  meetsThreshold,
  participationBps,
  percentageToScaled,
  totalVoted,
  type GovDecisionRule,
  type GovTallyCounts,
} from "./tally.ts";
export type {
  AccrualMarker,
  AccrualPoint,
  AlertArrearsFact,
  AlertIncidentFact,
  AlertRedemptionFact,
  BridgedSupplyRow,
  EffectiveYieldPoint,
  EpochRow,
  GovDecisionPolicy,
  GovExecutorResult,
  GovPolicyRow,
  GovProposalDetail,
  GovProposalRow,
  GovProposalsPayload,
  GovProposalStatus,
  GovTally,
  GovVoteOption,
  GovVoteRow,
  IncidentKind,
  IncidentRow,
  IncidentSeverity,
  MarketDepthBand,
  MarketSample,
  MarketSummary,
  OperatorEpochRow,
  OperatorPaymentRow,
  OperatorPaymentType,
  OperatorSummary,
  OperatorValidatorRow,
  PayoutStats,
  PortfolioHistoryState,
  PortfolioMetrics,
  PortfolioSummary,
  ProgramMetrics,
  RedemptionRow,
  RedemptionStatus,
  TransactionKind,
  TransactionRow,
  ValidatorRow,
  ValidatorSetHealth,
  ValidatorsPayload,
} from "./rows.ts";
export { HASH_EXPONENT, SHARE_EXPONENT, navHashPerShare } from "./amounts.ts";
