// @nvhash/api-types — the shared freshness-envelope contract for the nvHASH App
// (app plan PR 1.2, ADR-001 Decision 4). Producer: services/api. Consumers:
// services/api and apps/web. Zero runtime dependencies.

export {
  envelope,
  freshness,
  type Envelope,
  type FreshnessInput,
  type FreshnessMeta,
  type FreshnessSource,
} from "./envelope.ts";
export {
  GOVERNANCE_BOUNDED_FIELDS,
  MARKER_CAP,
  MARKER_CAP_WIRE,
  MAX_ACCRUAL_POINTS,
  MAX_ACCRUAL_POINTS_WIRE,
  MAX_BECH32_LENGTH,
  MAX_GOV_METADATA_LENGTH,
  MAX_GOV_POLICIES,
  MAX_GOV_POLICIES_WIRE,
  MAX_GOV_PROPOSAL_MESSAGES,
  MAX_GOV_PROPOSAL_MESSAGES_WIRE,
  MAX_GOV_PROPOSALS_PAGE,
  MAX_GOV_PROPOSALS_PAGE_WIRE,
  MAX_GOV_PROPOSERS,
  MAX_GOV_PROPOSERS_WIRE,
  MAX_GOV_SUMMARY_LENGTH,
  MAX_GOV_TITLE_LENGTH,
  MAX_GOV_VOTES_PER_PROPOSAL,
  MAX_GOV_VOTES_PER_PROPOSAL_WIRE,
  MAX_PROPOSAL_MESSAGES,
  MAX_PROPOSAL_METADATA_LEN,
  MAX_PROPOSAL_SUMMARY_LEN,
  MAX_PROPOSAL_TITLE_LEN,
  MAX_TXHASH_LENGTH,
  MAX_YIELD_POINTS,
  MAX_YIELD_POINTS_WIRE,
  WIRE_BOUNDS,
  WRITE_READ_BOUNDS,
  type WireBound,
  type WriteReadBound,
} from "./bounds.ts";
export {
  meetsThreshold,
  participationBps,
  percentageToScaled,
  totalVoted,
  type GovDecisionRule,
  type GovTallyCounts,
} from "./tally.ts";
export {
  type AccrualMarker,
  type AccrualPoint,
  type AlertArrearsFact,
  type AlertIncidentFact,
  type AlertRedemptionFact,
  type BridgedSupplyRow,
  type EffectiveYieldPoint,
  type EpochRow,
  type GovDecisionPolicy,
  type GovExecutorResult,
  type GovPolicyRow,
  type GovProposalDetail,
  type GovProposalRow,
  type GovProposalsPayload,
  type GovProposalStatus,
  type GovTally,
  type GovVoteOption,
  type GovVoteRow,
  type IncidentKind,
  type IncidentRow,
  type IncidentSeverity,
  type MarketDepthBand,
  type MarketSample,
  type MarketSummary,
  type OperatorEpochRow,
  type OperatorPaymentRow,
  type OperatorPaymentType,
  type OperatorSummary,
  type OperatorValidatorRow,
  type PayoutStats,
  type PortfolioHistoryState,
  type PortfolioMetrics,
  type PortfolioSummary,
  type ProgramMetrics,
  type RedemptionRow,
  type RedemptionStatus,
  type TransactionKind,
  type TransactionRow,
  type ValidatorRow,
  type ValidatorSetHealth,
  type ValidatorsPayload,
} from "./rows.ts";
export { HASH_EXPONENT, SHARE_EXPONENT, navHashPerShare } from "./amounts.ts";
